language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- tip

matrix:
  allow_failures:
  - go: tip

script:
- cat fixtures/infra.tf.json | go run main.go | go run main.go -reverse

before_deploy:
- export GOROOT_BOOTSTRAP=$GOROOT
- go get github.com/laher/goxc
- goxc -t -bc="linux darwin windows"
- goxc -d=./ -wd=./ -bc="linux darwin windows"

deploy:
  provider: releases
  api_key:
    secure: "I8c5DAt7koE4L8fzQncFyGSWbHNSzj3YeWuyGGB+fLc0W1JMorMwR5b+Phph7SDc51wtEKABE+ZSEaYjp0dHLi1wVl8Z+dqmhXtwW0Oo8n7t4SgWVd6u0/nC3nUP16D1aclzYks7CzFLdaG4NCyxC3wRYkEzXrVy7d1M2mr/SoXPoLnihh3AEf51hDadP006c1lYESpNJkalM9Y+sNiGjWdSOusz+KCVZ4U0bPaTlCRMCiJQgQJYCTomEAQFLR85gooJBre/395wxgzGgxq1noPkEzy3x5EDX1VgtOfGVUJapVzO2Q5mtOhISYop1PYjN2HP8AyGC6jv3+ADVgmU4rjLdWqLxqi4wzDhDOp7rVkfY/M8Iz3YMjEM1pPkjyXgeHf38DP4oyikptW3Px57M/gwoeMnDr3FTnPNO0oVIOn91rSsfzteY1KDXdbot/GJmBWy/WRN7g4XTiFgQu9hIu5Ibe4t91qedm58Xq/PmH2kHIS1ctp7tx968kIVZlasCZAN7Ka1eQdrURKtbUiBzo9rodrQ1L33YjT4cJkAkrcphi4VHYsDQ3E6J4GjodZKW9Ps8lhYSX5Prylx1tIXYcbFmMG2lweZJy8juoaZOAEYr1WAaT+TZ5OQhsUL0rOtN13SutBHL8yi/8EjrWylL3ov5M5DooHJnUaKQsBOokU="
  file:
  - snapshot/json2hcl_darwin_386.zip
  - snapshot/json2hcl_darwin_amd64.zip
  - snapshot/json2hcl_linux_386.tar.gz
  - snapshot/json2hcl_linux_amd64.tar.gz
  - snapshot/json2hcl_linux_arm.tar.gz
  - snapshot/json2hcl_snapshot_amd64.deb
  - snapshot/json2hcl_snapshot_armhf.deb
  - snapshot/json2hcl_snapshot_i386.deb
  - snapshot/json2hcl_windows_386.zip
  - snapshot/json2hcl_windows_amd64.zip
  skip_cleanup: true
  on:
    tags: true
    go: 1.5
    repo: kvz/json2hcl
